# Generated by Django 3.1 on 2020-08-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job', '0010_auto_20200814_0744'),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_answer', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], default='1', max_length=1)),
                ('for_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.question')),
            ],
        ),
    ]
