# Generated by Django 3.1.2 on 2020-11-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20201101_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choose_answer',
            field=models.CharField(max_length=1),
        ),
    ]
