# Generated by Django 3.1 on 2020-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='user_position',
            field=models.CharField(choices=[('HR', 'Human Resource'), ('I', 'Interviewee'), ('TL', 'Team Lead')], default='I', max_length=2),
        ),
    ]
