# Generated by Django 3.1 on 2020-08-13 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ManyToManyField(null=True, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
