# Generated by Django 3.1 on 2020-08-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0002_auto_20200813_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ManyToManyField(related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Job.jobs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='team_lead',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='team_lead',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
