# Generated by Django 3.1 on 2020-08-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0003_auto_20200813_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='jobs',
            name='team_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
