# Generated by Django 3.1 on 2020-08-14 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Job', '0005_auto_20200814_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ManyToManyField(default=1, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
