# Generated by Django 3.1 on 2020-08-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_application_selected_for_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='selected_for_interview',
            new_name='selected_for_exam',
        ),
    ]
