# Generated by Django 3.1.2 on 2020-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_auto_20200814_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='canceled_for_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='media\\cv'),
        ),
    ]
