# Generated by Django 3.1.2 on 2020-11-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_auto_20201101_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exam_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='obtained_marks',
            field=models.CharField(blank=True, default='0/0', max_length=10, null=True),
        ),
    ]
