# Generated by Django 3.1.2 on 2020-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_auto_20201102_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
